REM   Script: comandos de manipulação
REM   comandos de manipulação insert, where, update, select, set, delete

CREATE TABLE pais 
( 
    cd_pais number (2), 
    nm_pais char (45), 
    ds_nacionalidade char(35), 
    contraintpais_cd_pais_pk primary key (cd_pais), 
    constraintpais_nm_pais_ukunique (nm_pais) 
);

CREATE TABLE pais 
( 
    cd_pais number (2), 
    nm_pais char (45), 
    ds_nacionalidade char (35), 
    constraintpais_cd_pais_pk primary key (cd_pais), 
    constraintpais_nm_pais_ukunique (nm_pais) 
);

CREATE TABLE pais 
( 
    cd_pais number(2), 
    nm_pais char(45), 
    ds_nacionalidade char(35), 
    constraint pais_cd_pais_pk primary key (cd_pais), 
    constraint pais_nm_pais_ukunique (nm_pais) 
);

CREATE TABLE JOGADOR 
( 
    ID_JOGADOR NUMBER(10, 0) NOT NULL, 
    NOME       VARCHAR2(100) NOT NULL, 
    POSICAO    VARCHAR2(100), 
    BI         VARCHAR2(100), 
    CONSTRAINT PK_JOGADOR PRIMARY KEY (ID_JOGADOR) 
);

CREATE TABLE CONTRATADO 
( 
    ID_JOGADOR NUMBER(10, 0) NOT NULL, 
    DATA_INI   DATE NOT NULL, 
    DATA_FIM   DATE NOT NULL, 
    CONSTRAINT PK_CONTRATADO PRIMARY KEY (ID_JOGADOR, DATA_INI), 
    CONSTRAINT FK_CONTRATADO_REF_JOGADOR FOREIGN KEY (ID_JOGADOR) 
        REFERENCES JOGADOR(ID_JOGADOR), 
    CONSTRAINT CK_CONTRATADO CHECK (DATA_FIM > DATA_INI) 
);

ALTER TABLE JOGADOR   RENAME TO JOGADORES;

ALTER TABLE JOGADORES RENAME TO JOGADOR;

ALTER TABLE JOGADOR   ADD APELIDO VARCHAR2(30);

ALTER TABLE JOGADOR   RENAME COLUMN APELIDO TO NICKNAME;

ALTER TABLE JOGADOR   MODIFY POSICAO NUMBER(5, 0);

ALTER TABLE JOGADOR   DROP COLUMN BI CASCADE CONSTRAINT;

DESC JOGADOR


SELECT * FROM HR.EMPLOYEES;

SELECT EMPLOYYE_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT EMPLOYYES_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT EMPLOYYE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT * FROM HR.EMPLOYEES;

SELECT EMPLOYYE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT EMPLOYYE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT * FROM HR.EMPLOYEES;

SELECT EMPLOYYE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM HR.EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM HR.EMPLOYEES 
WHERE MANAGER_ID IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE MANAGER_ID IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE MANAGER_ID NOT IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE FIRST_NAME LIKE 'S%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE FIRST_NAME NOT LIKE 'S%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE SALARY BETWEEN 2500 AND 5000;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE SALARY NOT BETWEEN 2500 AND 5000;

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(1, 'JOGADOR 1', 2, 'JOGADOR TÁTICO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(2, 'JOGADOR 1', 2, 'JOGADOR TÁTICO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(1, 'JOGADOR 1', 1, 'GOLEIRO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(2, 'JOGADOR 2', 2, 'JOGADOR TÁTICO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(1, 'JOGADOR 1', 1, 'GOLEIRO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(1, 'JOGADOR 1', 2, 'JOGADOR TÁTICO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(2, 'JOGADOR 2', 1, 'GOLEIRO');

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(1, 'JOGADOR 1', 2, 'JOGADOR TÁTICO');

SELECT * FROM JOGADOR;

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(3, 'JOGADOR 2', 1, 'GOLEIRO');

SELECT * FROM JOGADOR;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INICIO, DATA_FIM) 
VALUES 
(3, TO_DATE('09-02-2018'), TO_DATE('09-02-2019');

SELECT * FROM CONTRATADO;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INICIO, DATA_FIM) 
VALUES 
(3,TO_DATE('09-02-2018'),TO_DATE('09-02-2019'));

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(3,TO_DATE('09-02-2018'),TO_DATE('09-02-2019'));

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('09-02-2019'),TO_DATE('09-02-2021'));

SELECT * FROM CONTRATADO;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('09-02-2019'),TO_DATE('09-02-2021'));

SELECT * FROM JOGADOR;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('09-02-2019'),TO_DATE('09-02-2021'));

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('09-02-2019'),TO_DATE('09-03-2021'));

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('09-2-2019'),TO_DATE('09-3-2021'));

SELECT * FROM HR.EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE MANAGER_ID IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE MANAGER_ID NOT IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE FIRST_NAME LIKE 'S%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE FIRST_NAME NOT LIKE 'S%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE SALARY BETWEEN 2500 AND 5000;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID 
FROM HR.EMPLOYEES 
WHERE SALARY NOT BETWEEN 2500 AND 5000;

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(1, 'JOGADOR 1', 2, 'JOGADOR TÁTICO') 
 
INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME) 
VALUES 
(3, 'JOGADOR 2', 1, 'GOLEIRO') 
 
INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('08-2-2019'),TO_DATE('09-3-2021'));

SELECT * FROM JOGADOR;

SELECT * FROM CONTRATADO;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('08-2-2019'),TO_DATE('09-3-2021'));

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,'08-2-2019','09-3-2021');

SELECT * FROM JOGADOR;

SELECT * FROM CONTRATADO;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,'08-2-2019','09-3-2021');

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,'08-02-2019','09-03-2021');

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,'08/02/2019','09/03/2021');

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(1,TO_DATE('05-06-2012', 'DD-MM-YYYY'),TO_DATE('05-06-2013', 'DD-MM-YYYY'));

SELECT * FROM CONTRATADO;

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INI, DATA_FIM) 
VALUES 
(3,TO_DATE('05-06-2015', 'DD-MM-YYYY'),TO_DATE('05-06-2018', 'DD-MM-YYYY'));

SELECT * FROM CONTRATADO;

UPDATE JOGADOR 
SET NOME = 'ALEXANDRE', POSICAO = 5 
WHERE ID_JOGADOR = 1;

SELECT * FROM CONTRATADO;

SELECT * FROM JOGADOR;

DELETE FROM CONTRATADO 
WHERE ID_JOGADOR = 3;

SELECT * FROM CONTRATADO;

